layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: aljabadi
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 8816796
  # telegram: your_username
  twitter: aljabadi
# unsplash: your_username
# vk: your_username
# website: http://your_website_url
# youtube: your_username

osprojects:
  - name: mixOmics Data Integration Project
    web_url: https://github.com/mixOmicsTeam/mixOmics
    image_url: assets/mixomics.png

  - name: BIRSBIO Datathon
    web_url: https://github.com/BIRSBiointegration/Hackathon
    image_url: https://avatars.githubusercontent.com/u/56370400?v=4

  - name: Easy Python Logging with logster
    web_url: https://github.com/aljabadi/logster
    image_url: https://www.sentinelone.com/wp-content/uploads/2018/07/19175338/Python-Scalyr-Colors-with-Log.png

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://www.wordstream.com/wp-content/uploads/2021/07/machine-learning.png

  - name: Data Science
    web_url: https://github.com/topics/data-science
    image_url: https://miro.medium.com/max/925/1*E1haIGB9K4K89PsFZgm-pw.jpeg

  - name: Hugging Face
    web_url: https://github.com/huggingface
    image_url: https://avatars.githubusercontent.com/u/25720743?s=200&v=4eg

  - name: Spark
    web_url: https://github.com/topics/spark
    image_url: https://raw.githubusercontent.com/github/explore/6f5025830918df26b37d23b3ffffbc35725fe15f/topics/spark/spark.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/121px-Python-logo-notext.svg.png

  - name: Kuberenetes
    web_url: https://github.com/kubernetes
    image_url: https://avatars.githubusercontent.com/u/13629408?s=200&v=4

  - name: Computer Vision
    web_url: https://github.com/topics/computer-vision

  - name: Julia
    web_url: https://github.com/topics/julia
    image_url: https://julialang.org/assets/infra/logo.svg

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png
